import {
  Activity,
  ArrowDownToLine,
  ArrowUpRight,
  BadgeCheck,
  Award,
  Blocks,
  Bot,
  BriefcaseBusiness,
  Building2,
  Camera,
  ChartNoAxesCombined,
  Check,
  Circle,
  CircleUserRound,
  ClipboardCheck,
  Clock3,
  CheckCircle2,
  CircleDashed,
  Cloud,
  Code2,
  Compass,
  Contact,
  Factory,
  FileText,
  Focus,
  FolderGit2,
  FolderKanban,
  GraduationCap,
  Handshake,
  Headphones,
  Image,
  GalleryHorizontalEnd,
  Globe2,
  Languages,
  Laptop,
  Lightbulb,
  ListChecks,
  Link,
  Mail,
  MapPin,
  MessageSquareText,
  MessageCircle,
  MonitorSmartphone,
  Network,
  Palette,
  PanelsTopLeft,
  PenTool,
  Phone,
  Route,
  Search,
  Send,
  Shirt,
  ShoppingBag,
  Sparkles,
  Store,
  Tags,
  Target,
  TimerReset,
  TrendingUp,
  UserRound,
  UsersRound,
  Users,
  WandSparkles,
  Workflow,
  Wrench,
  type LucideIcon,
  type LucideProps,
} from "lucide-react";
import { createElement } from "react";

const iconMap: Record<string, LucideIcon> = {
  activity: Activity,
  arrowDownload: ArrowDownToLine,
  arrowExternal: ArrowUpRight,
  badge: BadgeCheck,
  award: Award,
  "badge-check": BadgeCheck,
  "book-open": FileText,
  blocks: Blocks,
  bot: Bot,
  briefcase: BriefcaseBusiness,
  building: Building2,
  camera: Camera,
  chart: ChartNoAxesCombined,
  check: Check,
  "check-circle-2": CheckCircle2,
  "circle-dashed": CircleDashed,
  clipboard: ClipboardCheck,
  clock: Clock3,
  code: Code2,
  "code-2": Code2,
  compass: Compass,
  contact: Contact,
  factory: Factory,
  file: FileText,
  "file-down": ArrowDownToLine,
  "file-text": FileText,
  focus: Focus,
  folder: FolderKanban,
  folderGit: FolderGit2,
  "folder-git-2": FolderGit2,
  graduation: GraduationCap,
  "graduation-cap": GraduationCap,
  handshake: Handshake,
  headphones: Headphones,
  image: Image,
  "gallery-horizontal-end": GalleryHorizontalEnd,
  github: FolderGit2,
  "globe-2": Globe2,
  languages: Languages,
  laptop: Laptop,
  lightbulb: Lightbulb,
  linkedin: Contact,
  "list-checks": ListChecks,
  link: Link,
  mail: Mail,
  mapPin: MapPin,
  "map-pin": MapPin,
  message: MessageSquareText,
  "message-circle": MessageCircle,
  "monitor-smartphone": MonitorSmartphone,
  network: Network,
  palette: Palette,
  panels: PanelsTopLeft,
  pen: PenTool,
  phone: Phone,
  profile: CircleUserRound,
  route: Route,
  search: Search,
  send: Send,
  shirt: Shirt,
  shopping: ShoppingBag,
  "shopping-bag": ShoppingBag,
  sparkles: Sparkles,
  store: Store,
  tags: Tags,
  target: Target,
  timer: TimerReset,
  trending: TrendingUp,
  user: UserRound,
  "user-round": UserRound,
  users: Users,
  "users-round": UsersRound,
  "building-2": Building2,
  "briefcase-business": BriefcaseBusiness,
  "chart-no-axes-combined": ChartNoAxesCombined,
  "heart-handshake": Handshake,
  "layers-3": Blocks,
  "settings-2": Wrench,
  "tool-case": Wrench,
  cloud: Cloud,
  wand: WandSparkles,
  workflow: Workflow,
  wrench: Wrench,
};

export function resolveIcon(name?: string): LucideIcon {
  if (!name) return Circle;
  return iconMap[name] ?? Circle;
}

export function PortfolioIconGlyph({ name, ...props }: LucideProps & { name?: string }) {
  return createElement(resolveIcon(name), props);
}
